### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 11 next listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by jmg1138** [nothingworksright/unblinkingPi#8]
Occasionally see this error when using [external-ip](https://github.com/J-Chaniotis/external-ip)  
```
Trace
    at addListener (events.js:252:17)
    at getIP.sequential (/home/user/git/unblinkingPi/node_modules/external-ip/lib/extIP.js:46:18)
    at Object.getExternalIp [as enoughDurationOrNot] (/home/user/git/unblinkingPi/unblinkingip.js:59:9)
    at Object.enoughDurationOrNot [as durationSinceLastCheck] (/home/user/git/unblinkingPi/unblinkingip.js:52:22)
    at setUsingLastCheck (/home/user/git/unblinkingPi/unblinkingip.js:18:26)
    at /home/user/git/unblinkingPi/unblinkingip.js:36:25
    at /home/user/git/unblinkingPi/node_modules/level-pathwise/index.js:117:5
    at /home/user/git/unblinkingPi/node_modules/stream-to-array/index.js:54:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(node) warning: possible EventEmitter memory leak detected. 11 done listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:252:17)
    at getIP.sequential (/home/user/git/unblinkingPi/node_modules/external-ip/lib/extIP.js:56:14)
    at Object.getExternalIp [as enoughDurationOrNot] (/home/user/git/unblinkingPi/unblinkingip.js:59:9)
    at Object.enoughDurationOrNot [as durationSinceLastCheck] (/home/user/git/unblinkingPi/unblinkingip.js:52:22)
    at setUsingLastCheck (/home/user/git/unblinkingPi/unblinkingip.js:18:26)
    at /home/user/git/unblinkingPi/unblinkingip.js:36:25
    at /home/user/git/unblinkingPi/node_modules/level-pathwise/index.js:117:5
    at /home/user/git/unblinkingPi/node_modules/stream-to-array/index.js:54:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jmg1138** [comment]
Here are lines 44 through 60 from [external-ip /lib/extIP.js](https://github.com/J-Chaniotis/external-ip/blob/master/lib/extIP.js#L46)
```
sequential: function (cb) {

            loop.on('next', function (service, i, arr, errors) {
                service.getIP(function (err, ip) {
                    if (err) {
                        errors.push(service.url + ' : ' + err);
                        loop.next(errors);
                    } else {
                        loop.done(null, ip);
                    }
                });
            })
            .on('done', function (errors, ip) {
                cb.apply(null, ip ? [null, ip] : [errors, null]);
            })
            .start([]);
},
```

**Comment by jmg1138** [comment]
Possibly could resolve by changing `.on` to `.once`
